import fs from 'fs'
import path from 'path'
import matter from 'gray-matter'
import marked from 'marked'
import Head from 'next/head'
import Link from 'next/link'
import styled from 'styled-components'
import NavLink from './../../components/NavLink'

const NavStyle = styled.nav`
a {
        &[aria-current] {
            color: #cccccc;
    }
}`; 

export default function PostPage({
    frontmatter: { title, date },
    slug,
    content,
  }) {
    return (
      <>
      <NavStyle className="lang">
        <NavLink href={`/posts/${slug.split('-en')[0].split('-tr')[0]}-tr`}><a className="lang_tr">TR</a></NavLink>
          |
        <NavLink href={`/posts/${slug.split('-tr')[0].split('-en')[0]}-en`}><a className="lang_en">EN</a></NavLink>
      </NavStyle>
      
      <div className="container">
        <Head>
          <title>{slug.split('-en')[0].split('-tr')[0]}</title>
          <meta name="description" content="Generated by create next app" />
          <link rel = "icon" href = "https://image.flaticon.com/icons/png/512/2639/2639672.png" />
          <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css" integrity="sha512-1ycn6IcaQQ40/MKBW2W4Rhis/DbILU74C1vSrLJxCq57o941Ym01SwNsOMqvEBFlcgUa6xLiPY/NS5R+E6ztJQ==" crossOrigin="anonymous" referrerpolicy="no-referrer" />
        </Head>

        <div className='block block-inside'>
          <h1 className='post-title'>{title}</h1>
          <div className='post-date'>Posted on {date}</div>
          <div className='post-body'>
            <div dangerouslySetInnerHTML={{ __html: marked(content) }}></div>
          </div>
        </div>
      </div>  
      </>
    )
  }
  
  export async function getStaticPaths() {
    const files = fs.readdirSync(path.join('posts'))
  
    const paths = files.map((filename) => ({
      params: {
        slug: filename.replace('.md', ''),
      },
    }))
    
    return {
      paths,
      fallback: false,
    }
  }
  
  export async function getStaticProps({ params: { slug } }) {
    const markdownWithMeta = fs.readFileSync(
      path.join('posts', slug + '.md'),
      'utf-8'
    )
  
    const { data: frontmatter, content } = matter(markdownWithMeta)
    return {
      props: {
        frontmatter,
        slug,
        content,
      },
    }
  }
  