import React from "react";
import Head from 'next/head'
import Image from 'next/image'
import Link from "next/link"
import styles from "../styles/Home.module.css"
import NavLink from './../components/NavLink'
import styled from 'styled-components'

const NavStyle = styled.nav`
a {
        &[aria-current] {
            color: #cccccc;
    }
}`; 


export default function Contact() {
    return (
        <>
        <NavStyle className="lang">
            <NavLink href="/about"><a className="lang_tr">TR</a></NavLink>
            |
            <NavLink href="/about-en"><a className="lang_en">EN</a></NavLink>
        </NavStyle>
        
        <div className="container">
            <Head>
                <title>About</title>
                <meta name="description" content="Generated by create next app" />
                <link rel = "icon" href = "https://image.flaticon.com/icons/png/512/2639/2639672.png" />
                <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css" integrity="sha512-1ycn6IcaQQ40/MKBW2W4Rhis/DbILU74C1vSrLJxCq57o941Ym01SwNsOMqvEBFlcgUa6xLiPY/NS5R+E6ztJQ==" crossOrigin="anonymous" referrerpolicy="no-referrer" />
            </Head>
            
            <div className={styles.about_container}>
            <h2>About Me</h2>
                <p>
                    My name is Batuhan. I live in in Istanbul. I am a senior
                    at the Gebze Technical University, and soon to be electronic engineer.
                    As a summary of my university life, I have encountered software in 
                    the first year and continued to progress every day by putting on the 
                    fundamental knowledge that I learned in school. 
                    <p>
                    During this time, I worked on the python language and improved 
                    myself in various areas such as image processing, machine learning 
                    and signal processing with Python. In addition I made a robot arm 
                    and various projects with Arduino.
                    </p>
                    <p>
                    C/C++, Matlab and Python are programming languages that I am good at.
                    Also I am familiar with HTML, CSS and a bit of Flutter.
                    </p>
                    <p>
                    I love the internet, technology, and building beautiful things.
                    Some of my favorite things to do are read, 
                    coding and learning new things.
                    </p>
                    <p>
                    My career aspirations are to have a professional career in software 
                    development as well as to improve myself in machine learning and
                    deep learning. 
                    </p>
                </p>
    
                <h2>Schools</h2>
                <ul>
                    <li>Okyanus College            (2017)</li>
                    <li>Gebze Technical University (2017-2022)</li>
                </ul>
                <h2>Experiences</h2>
                <ul>
                    <li>ASELSAN <span>&#8203;</span> (15.08.2020 - 11.09.2020)</li>
                    <li>Ardıctech (05.07.2021 - )</li>
                </ul>
                </div>
        </div>
    </>
    )
}