import React from "react";
import Head from 'next/head'
import Image from 'next/image'
import Link from "next/link"
import styles from "../styles/Home.module.css"
import NavLink from './../components/NavLink'
import styled from 'styled-components'

const NavStyle = styled.nav`
a {
        &[aria-current] {
            color: #cccccc;
    }
}`; 

export default function Contact() {
    return (
        <>
        <NavStyle className="lang">
            <NavLink href="/about"><a className="lang_tr">TR</a></NavLink>
            |
            <NavLink href="/about-en"><a className="lang_en">EN</a></NavLink>
        </NavStyle>

        <div className="container">
            <Head>
                <title>About</title>
                <meta name="description" content="Generated by create next app" />
                <link rel = "icon" href = "https://image.flaticon.com/icons/png/512/2639/2639672.png" />
                <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css" integrity="sha512-1ycn6IcaQQ40/MKBW2W4Rhis/DbILU74C1vSrLJxCq57o941Ym01SwNsOMqvEBFlcgUa6xLiPY/NS5R+E6ztJQ==" crossorigin="anonymous" referrerpolicy="no-referrer" />
            </Head>
            <div className={styles.about_container}>
            <h2>Hakkımda</h2>
                <p className={styles.blog_text_in}>
                    Merhabalar, ben Batuhan. Gebze Teknik Üniversitesi elektronik 
                    mühendisliği son sınıf öğrencisiyim ve
                    önümüzdeki dönem sonunda mezun olacağım. Üniversite hayatımın bir
                    özeti olarak, 1.sınıfta yazılımla tanıştım ve bu alanda okulda
                    öğrendiğim temel bilgilerin üzerine katarak her gün ilerlemeyi sürdürdüm.
                    <p>
                    Bu süreçte, python dili üzerinde
                    çalışmalar yaptım ve Python ile görüntü işleme, makine öğrenmesi, 
                    sinyal işleme gibi çeşitli alanlarda kendimi geliştirdim.
                    Arduino ile robot kol ve çeşitli projeler yaptım. 
                    </p>
                    <p>
                    C/C++, Matlab ve Python iyi olduğum programlama dilleridir. Ayrıca HTML, CSS
                    ve Flutter hakkında da bilgi sahibiyim.
                    </p>
                    Bundan sonraki kariyer hedeflerime, profesyonel olarak
                    yazılım geliştirmenin yanı sıra makine öğrenmesi ve 
                    derin öğrenme alanlarında da kendimi geliştirerek devam 
                    etmek istiyorum.
                </p>

                <h2>Okullar</h2>
                <ul>
                    <li>Okyanus Koleji (2017)</li>
                    <li>Gebze Teknik Üniversi (2017-2022)</li>
                </ul>
                <h2>Deneyimler</h2>
                <ul>
                    <li>ASELSAN <span>&#8203;</span> (15.08.2020 - 11.09.2020)</li>
                    <li>Ardıctech (05.07.2021 - )</li>
                </ul>
                </div>
        </div>
    </>
    )
}