import React from "react";
import Head from 'next/head'
import path from "path";
import fs from "fs";
import matter from 'gray-matter'
import styles from '../styles/Home.module.css'
import Link from "next/link"
import { sortByDate } from './../utils'
import Post from '../components/Post'
import NavLink from '../components/NavLink'

export default function Home({ posts }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel = "icon" href = "https://image.flaticon.com/icons/png/512/2639/2639672.png" />
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css" integrity="sha512-1ycn6IcaQQ40/MKBW2W4Rhis/DbILU74C1vSrLJxCq57o941Ym01SwNsOMqvEBFlcgUa6xLiPY/NS5R+E6ztJQ==" crossOrigin="anonymous" referrerpolicy="no-referrer" />
      </Head>
    
    {posts.map((post, index) => (
      <div className={styles.blog_out}>
          <Post key={index} post={post} />
      </div>
    ))}
    </div>
  )
}

export async function getStaticProps() {
  // Get files from the posts dir
  const files = fs.readdirSync(path.join('posts'))
  files.forEach(function (item, index, object) {
    if ( item.includes("-tr") ){
      files.splice(index, 1)
    }
  })

  // Get slug and frontmatter from posts
  const posts = files.map((filename) => {
    // Create slug
    const slug = filename.replace('.md', '')

    // Get frontmatter
    const markdownWithMeta = fs.readFileSync(
      path.join('posts', filename),
      'utf-8'
    )

    const { data: frontmatter } = matter(markdownWithMeta)

    return {
      slug,
      frontmatter,
    }
  })

  return { 
    props: {
      posts: posts.sort(sortByDate),
    },
  }
}


// Home.getInitialProps = async ({ req }) => {
//   const res = await fetch("http://localhost:3000/api/posts");
//   const json = await res.json();
//   return { posts: json.posts };
// };
